slug: emnlp-2025
date: 2025-11-05
category: publication
title:
  zh: 一篇论文被 EMNLP 2025 Findings 接收
  en: A Paper Accepted to EMNLP 2025 Findings
excerpt:
  zh: 一作刘之辰同学提出用惊讶度谱距离评估文本生成质量的研究被 EMNLP 2025 Findings 接收。
  en: Our work on evaluating text generation with spectral distances of surprisal was accepted to EMNLP 2025 Findings.
featured: false
draft: false
locales:
  - zh
  - en
